[defaults]
format = " {name} {time}\n"

[[sessions]]
id = "work-1"
name = "Work"
duration = "25m"
command = "$HOME/.local/bin/uair-notify work"

[[sessions]]
id = "break-1"
name = "Break"
duration = "5m"
command = "$HOME/.local/bin/uair-notify break"

[[sessions]]
id = "work-2"
name = "Work"
duration = "25m"
command = "$HOME/.local/bin/uair-notify work"

[[sessions]]
id = "break-2"
name = "Break"
duration = "5m"
command = "$HOME/.local/bin/uair-notify break"

[[sessions]]
id = "work-3"
name = "Work"
duration = "25m"
command = "$HOME/.local/bin/uair-notify work"

[[sessions]]
id = "break-3"
name = "Break"
duration = "5m"
command = "$HOME/.local/bin/uair-notify break"

[[sessions]]
id = "work-4"
name = "Work"
duration = "25m"
command = "$HOME/.local/bin/uair-notify work"

[[sessions]]
id = "long-break"
name = "Long Break"
duration = "15m"
command = "$HOME/.local/bin/uair-notify cycle"
